# Site settings
title: Edo Airoldi
email: airoldi@temple.edu
description: > # this means to ignore newlines until "baseurl:"
  Millard E. Gladfelter Professor of Statistics & Data Science, Professor of Finance (by courtesy), Co-Director of the Temple Data Science Institute, Fox School of Business, Temple University
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://airoldi.github.io" # the base hostname & protocol for your site
github_username:  airoldi
orchid_id:  0000-0002-3512-0542
arxiv_url:  "https://arxiv.org/a/airoldi_e_1"
google_scholar_id: XKCyZk0AAAAJ&hl
# twitter_username:  airoldi

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Millard E. Gladfelter Professor of Statistics & Data Science, Professor of Finance (by courtesy)"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
