# Site settings
title: Edo Airoldi
email: airoldi@temple.edu
description: > # this means to ignore newlines until "baseurl:"
  Millard E. Gladfelter Professor of Statistics & Data Science, Professor of Finance (by courtesy), Co-Director of the Temple Data Science Institute, Fox School of Business, Temple University
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://airoldi.github.io" # the base hostname & protocol for your site
twitter_username: airoldi
github_username:  airoldi
arxiv_url: " http://arxiv.org/a/airoldi_e_1"
orcid: 0000-0002-3512-0542
#author:

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Millard E. Gladfelter Professor of Statistics & Data Science, Professor of Finance (by courtesy)"
excerpt_separator: "<!--more-->"

google_analytics: UA-57660811-2 

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
